# Generated by Django 2.0.10 on 2019-02-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Anders', max_length=100)),
                ('last_name', models.CharField(help_text='Friis', max_length=100)),
                ('klassetrin', models.CharField(help_text='År hvor deres klasse startede i syvende', max_length=4)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['klassetrin', 'first_name', 'last_name'],
            },
        ),
    ]
