# Generated by Django 2.0.10 on 2019-02-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='date_of_birth',
        ),
    ]
