# Generated by Django 2.0.10 on 2019-02-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_mentee_mentorgruppe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorgroup',
            old_name='mentor',
            new_name='mentor_group',
        ),
        migrations.RenameField(
            model_name='mentorgroup',
            old_name='name',
            new_name='name_group',
        ),
    ]
