# Generated by Django 2.0.10 on 2019-02-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190206_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorgroup',
            options={'ordering': ['name_group']},
        ),
        migrations.RemoveField(
            model_name='mentorgroup',
            name='mentor_group',
        ),
    ]
