# Generated by Django 2.0.10 on 2019-02-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_mentorgroup_mentor_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorgroup',
            options={'ordering': ['name_group']},
        ),
        migrations.RemoveField(
            model_name='mentorgroup',
            name='last_name',
        ),
    ]
