# Generated by Django 2.0.10 on 2019-02-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190206_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorgroup',
            options={},
        ),
        migrations.RenameField(
            model_name='mentorgroup',
            old_name='mentor_group',
            new_name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorgroup',
            name='name_group',
        ),
        migrations.AddField(
            model_name='mentorgroup',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Group name'),
            preserve_default=False,
        ),
    ]
